import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h3>
          <a href="http://localhost:8000/oauth?response_type=code&client_id=client5678&redirect_url=http://localhost:3002/callback">
            Admin - Sign in with Authorization Server
          </a>
        </h3>
      </main>
    </>
  );
}
